abhaynikam/boring_generators

CHANGELOG.md
README.md
lib/generators/boring/favicon/build/build_generator.rb
lib/generators/boring/favicon/build/templates/favicon.html.erb.tt
test/generators/favicon_build_generator_test.rb

PR adds a generator helpful to generate favicons of all sizes using ImageMagick. Provide a couple of options to like using the existing primary logo image or use the favico letter with the proper color.

Add favicon generator

---

CHANGELOG.md
README.md
lib/generators/boring/simple_form/install/install_generator.rb
test/generators/simple_form_install_generator_test.rb

Adds generator to install simple_form: https://github.com/heartcombo/simple_form

Adds simple_form install generator

---

CHANGELOG.md
README.md
lib/generators/boring/devise/install/install_generator.rb
test/generators/devise_install_generator_test.rb

This can be improved. Doing the basic setup for now. We can add some basic themes and make it easier not deal with what login/sign-up page design should look like.

Adds the devise install generator

---

CHANGELOG.md
lib/generators/boring/tailwind/install/install_generator.rb
lib/generators/boring/tailwind/install/templates/README
test/generators/tailwind_install_generator_test.rb

Updates the tailwind css generator to support tailwind 2.0

---

lib/generators/boring/oauth/base_generator.rb

Tweak omniauth generator User#from_omniauth to avoid saving user name

---

lib/generators/boring/oauth/facebook/install/templates/README
lib/generators/boring/oauth/github/install/templates/README
lib/generators/boring/oauth/google/install/templates/README
lib/generators/boring/oauth/twitter/install/templates/README

Add hint for callback URL in the post oauth installation message

---

CHANGELOG.md
README.md
lib/generators/boring/rails_admin/install/install_generator.rb
test/generators/rails_admin_install_generator_test.rb

Add generator for: https://github.com/sferik/rails_admin

Adds rails-admin generator

---

CHANGELOG.md
README.md
lib/generators/boring/paper_trail/install/install_generator.rb
lib/generators/boring/rails_admin/install/install_generator.rb
test/generators/paper_trail_install_generator_test.rb

Add generator for: https://github.com/paper-trail-gem/paper_trail

Add paper trail generator

---

CHANGELOG.md
lib/generators/boring/bootstrap/install/install_generator.rb

Update bootstrap generator to support Bootstrap 5

---

CHANGELOG.md
README.md
lib/generators/boring/factory_bot/install/install_generator.rb
lib/generators/boring/factory_bot/install/templates/users.rb
lib/generators/boring/faker/install/install_generator.rb
lib/generators/boring/rspec/install/install_generator.rb
lib/generators/boring/rubocop/install/install_generator.rb
test/generators/factory_bot_install_generator_test.rb
test/generators/faker_install_generator_test.rb
test/generators/rspec_install_generator_test.rb

PR adds: 
- Rspec generator
- Faker generator
- FactoryBot generator

Add rspec generator

---

CHANGELOG.md
CONTRIBUTING.md
README.md
lib/generators/boring/rswag/install/install_generator.rb
lib/generators/boring/rswag/install/templates/README
test/generator_helper.rb
test/generators/rswag_install_generator_test.rb
tmp/templates/app_template/config/boot.rb

Tasks
---
- Add generator for rswag gem
- Sort generators in the Readme in alphabetical order

Add generator for rswag gem

---

CHANGELOG.md
README.md
lib/generators/boring/rack_mini_profiler/install/install_generator.rb
test/generators/rack_mini_profiler_install_generator_test.rb

Generator for rack mini profiler

---

Gemfile.lock
lib/generators/boring/rack_mini_profiler/install/install_generator.rb

Refactors the rack-mini-profiler installer.
- Adds the gem in development group.

Refactor the rack-mini-profiler gem

---

lib/boring_generators/generator_helper.rb
lib/generators/boring/pronto/base_generator.rb
lib/generators/boring/pronto/gitlab_ci/install/install_generator.rb

This PR refactors the pronto gem installers

Refactors pronto gem installer

---

CHANGELOG.md
README.md
lib/generators/boring/vcr/install/install_generator.rb
lib/generators/boring/vcr/install/templates/rspec/vcr.rb.tt
test/generators/vcr/vcr_install_generator_test.rb

- Generator for Doorkeeper with devise

add generator for the VCR

---

CHANGELOG.md
README.md
lib/generators/boring/devise/doorkeeper/install/install_generator.rb
test/generators/devise/doorkeeper_devise_install_generator_test.rb

- Generator for Doorkeeper with devise

Implement the generator for doorkeeper with devise

---

CHANGELOG.md
README.md
lib/generators/boring/avo/install/install_generator.rb
test/generators/avo_install_generator_test.rb

Generator for Avo

---

CHANGELOG.md
README.md
lib/generators/boring/figjam/install/install_generator.rb
test/generators/figjam_install_generator_test.rb

Generator for Figjam

---

CHANGELOG.md
README.md
lib/generators/boring/dotenv/install/install_generator.rb
lib/generators/boring/dotenv/install/templates/.env
test/generators/dotenv_install_generator_test.rb

Generator for dotenv

---

CHANGELOG.md
README.md
lib/generators/boring/honeybadger/install/install_generator.rb
lib/generators/boring/honeybadger/install/templates/README
lib/generators/boring/honeybadger/install/templates/honeybadger.yml.tt
test/generators/honeybadger_install_generator_test.rb

Generator for honeybadger

---

lib/generators/boring/vcr/install/install_generator.rb
test/generators/vcr/vcr_install_generator_test.rb

Tasks
---
- Make minitest the default test library
- Update code to check required files for test library so they run only for their respective test library
- Update test as required to make them pass

Fix VCR generator

---

CHANGELOG.md
README.md
lib/generators/boring/rails_erd/install/install_generator.rb
test/generators/rails_erd_install_generator_test.rb

Generator for rails erd

---

CHANGELOG.md
README.md
lib/generators/boring/cancancan/install/install_generator.rb
test/generators/cancancan/cancancan_install_generator_test.rb

add generator for the cancancan
